import { z } from "zod";
import { ActionSchema } from "../ai/dialogue/schema.js";
import { PLACEMENTS, STRUCTURE_KINDS } from "../ai/director/schemas.js";
import { PackOverrideSchema } from "../core/content/schema.js";
import { ARTIFACT_VERSION } from "./artifact.js";

/**
 * What a scenario file on disk is allowed to contain.
 *
 * These validate the *persisted* shapes, which are not the same as the director's
 * response schemas: a `SiteSpec` carries its own `siteId` and a nested
 * `SettlementSpec`, whereas the model is asked for a flatter thing that the
 * director then assembles. Sharing the enums keeps the closed sets closed —
 * an artifact cannot smuggle in a structure kind the generator has no plan for,
 * however it was produced.
 *
 * An artifact is data from outside the program: it may have been hand-edited,
 * generated by an older build, or truncated by a full disk. It gets parsed, not
 * cast.
 */

const BoundaryStyleSchema = z.enum(["ocean", "cliffs", "mountains"]);

export const WorldBoundsSchema = z.object({
	minX: z.number().int(),
	minY: z.number().int(),
	maxX: z.number().int(),
	maxY: z.number().int(),
	style: BoundaryStyleSchema,
	thickness: z.number().int().min(1).max(64),
});

export const ScenarioBriefSchema = z.object({
	premise: z.string().optional(),
	setting: z.string().optional(),
	storyline: z.string().optional(),
	tone: z.string().optional(),
	protagonist: z.string().optional(),
	avoid: z.string().optional(),
	duration: z.enum(["short", "medium", "long"]).optional(),
});

export const StoredWorldLoreSchema = z.object({
	title: z.string(),
	premise: z.string(),
	era: z.string(),
	tone: z.string(),
	factions: z.array(z.string()),
	deities: z.array(z.string()),
});

export const StoredRegionSpecSchema = z.object({
	id: z.string(),
	name: z.string(),
	blurb: z.string(),
	tone: z.string(),
	culture: z.string(),
	factionName: z.string().optional(),
	lore: z.array(z.string()),
	ambient: z.array(z.string()),
});

const StoredStructureSchema = z.object({
	kind: z.enum(STRUCTURE_KINDS),
	size: z.enum(["small", "medium", "large"]),
	importance: z.number().int().min(1).max(5),
	name: z.string().optional(),
	signText: z.string().optional(),
});

export const StoredSettlementSpecSchema = z.object({
	name: z.string(),
	walled: z.boolean(),
	structures: z.array(StoredStructureSchema),
});

export const StoredNpcSpecSchema = z.object({
	slot: z.number().int().min(0),
	name: z.string(),
	role: z.string(),
	glyph: z.string().regex(/^[A-Za-z]$/),
	appearance: z.string(),
	persona: z.string(),
	disposition: z.number().int().min(-100).max(100),
	placement: z.enum(PLACEMENTS),
	structureName: z.string().optional(),
	knows: z.array(z.string()),
});

export const StoredSiteSpecSchema = z.object({
	siteId: z.number().int(),
	name: z.string(),
	shortName: z.string(),
	description: z.string(),
	settlement: StoredSettlementSpecSchema,
	npcs: z.array(StoredNpcSpecSchema),
	hooks: z.array(z.string()),
});

const ObjectiveSchema = z.object({
	kind: z.enum(["reach", "talk", "have", "flag"]),
	target: z.string().min(1),
	quantity: z.number().int().min(1).optional(),
	done: z.boolean(),
});

/**
 * A full screen of prose.
 *
 * Bounded generously but bounded: this is the one place in the game allowed to be
 * long, and the renderer elides what will not fit rather than growing the frame, so
 * a card nobody bounded would simply lose its ending.
 */
export const CardBodySchema = z.object({
	title: z.string().min(1).max(120),
	subtitle: z.string().max(160).optional(),
	sections: z
		.array(
			z.object({
				heading: z.string().min(1).max(40),
				body: z.string().min(1).max(900),
			}),
		)
		.min(1)
		.max(4),
});

export const ScenarioBeatSchema = z.object({
	id: z.string().min(1).max(64),
	order: z.number().int().min(0),
	siteId: z.number().int(),
	npcSlot: z.number().int().min(0),
	requires: z.array(z.string().min(1)),
	setsFlag: z.string().min(1),
	quest: z
		.object({
			id: z.string().min(1).max(64),
			name: z.string().min(1),
			description: z.string(),
			objectives: z.array(ObjectiveSchema),
		})
		.optional(),
	journal: z.string().optional(),
	card: CardBodySchema.optional(),
});

export const ScenarioArcSchema = z.object({
	title: z.string().min(1).max(120),
	premise: z.string().max(600),
	beats: z.array(ScenarioBeatSchema),
	ending: CardBodySchema.optional(),
});

const DialogueChoiceSchema = z.object({
	text: z.string().min(1).max(120),
	goto: z.string().max(64).nullable(),
	requires: z.array(z.string().min(1)).optional(),
});

export const DialogueNodeSchema = z.object({
	id: z.string().min(1).max(64),
	speech: z.string().max(600),
	requires: z.array(z.string().min(1)).optional(),
	choices: z.array(DialogueChoiceSchema).max(6),
	actions: z.array(ActionSchema).max(3).optional(),
});

export const DialogueTreeSchema = z.object({
	npcId: z.string().min(1),
	entry: z.array(z.string().min(1)).min(1),
	revisit: z.array(z.string().min(1)).optional(),
	nodes: z.record(z.string(), DialogueNodeSchema),
});

export const ScenarioArtifactSchema = z.object({
	artifactVersion: z.literal(ARTIFACT_VERSION),
	id: z
		.string()
		.min(1)
		.max(64)
		// The id is a filename stem and a value written into saves, so it must not be
		// able to walk out of the scenarios directory.
		.regex(/^[a-z0-9][a-z0-9-]*$/, "lower-case letters, digits and dashes only"),
	title: z.string().min(1).max(80),
	blurb: z.string().max(400),
	brief: ScenarioBriefSchema,
	// A pack name, resolved against `.packs/`. Constrained like the scenario id
	// because it becomes a filename, and a name that can walk up out of the packs
	// directory would let a scenario file choose what gets read.
	pack: z
		.string()
		.min(1)
		.max(64)
		.regex(/^[a-z0-9][a-z0-9-]*$/, "lower-case letters, digits and dashes only")
		.optional(),
	content: PackOverrideSchema.optional(),
	seed: z.number().int(),
	spawn: z.object({ x: z.number().int(), y: z.number().int() }),
	bounds: WorldBoundsSchema,
	lore: StoredWorldLoreSchema,
	regions: z.record(z.string(), StoredRegionSpecSchema),
	sites: z.record(z.string(), StoredSiteSpecSchema),
	arc: ScenarioArcSchema.optional(),
	trees: z.record(z.string(), DialogueTreeSchema).optional(),
	authoredWith: z.object({
		models: z.record(z.string(), z.string()),
		calls: z.number().int().min(0),
		at: z.string(),
	}),
});
