import { z } from "zod";
import { PLACEMENTS, STRUCTURE_KINDS } from "../ai/director/schemas.js";
import { ARTIFACT_VERSION } from "./artifact.js";

/**
 * What a scenario file on disk is allowed to contain.
 *
 * These validate the *persisted* shapes, which are not the same as the director's
 * response schemas: a `SiteSpec` carries its own `siteId` and a nested
 * `SettlementSpec`, whereas the model is asked for a flatter thing that the
 * director then assembles. Sharing the enums keeps the closed sets closed —
 * an artifact cannot smuggle in a structure kind the generator has no plan for,
 * however it was produced.
 *
 * An artifact is data from outside the program: it may have been hand-edited,
 * generated by an older build, or truncated by a full disk. It gets parsed, not
 * cast.
 */

const BoundaryStyleSchema = z.enum(["ocean", "cliffs", "mountains"]);

export const WorldBoundsSchema = z.object({
	minX: z.number().int(),
	minY: z.number().int(),
	maxX: z.number().int(),
	maxY: z.number().int(),
	style: BoundaryStyleSchema,
	thickness: z.number().int().min(1).max(64),
});

export const ScenarioBriefSchema = z.object({
	premise: z.string().optional(),
	setting: z.string().optional(),
	storyline: z.string().optional(),
	tone: z.string().optional(),
	protagonist: z.string().optional(),
	avoid: z.string().optional(),
	duration: z.enum(["short", "medium", "long"]).optional(),
});

export const StoredWorldLoreSchema = z.object({
	title: z.string(),
	premise: z.string(),
	era: z.string(),
	tone: z.string(),
	factions: z.array(z.string()),
	deities: z.array(z.string()),
});

export const StoredRegionSpecSchema = z.object({
	id: z.string(),
	name: z.string(),
	blurb: z.string(),
	tone: z.string(),
	culture: z.string(),
	factionName: z.string().optional(),
	lore: z.array(z.string()),
	ambient: z.array(z.string()),
});

const StoredStructureSchema = z.object({
	kind: z.enum(STRUCTURE_KINDS),
	size: z.enum(["small", "medium", "large"]),
	importance: z.number().int().min(1).max(5),
	name: z.string().optional(),
	signText: z.string().optional(),
});

export const StoredSettlementSpecSchema = z.object({
	name: z.string(),
	walled: z.boolean(),
	structures: z.array(StoredStructureSchema),
});

export const StoredNpcSpecSchema = z.object({
	slot: z.number().int().min(0),
	name: z.string(),
	role: z.string(),
	glyph: z.string().regex(/^[A-Za-z]$/),
	appearance: z.string(),
	persona: z.string(),
	disposition: z.number().int().min(-100).max(100),
	placement: z.enum(PLACEMENTS),
	structureName: z.string().optional(),
	knows: z.array(z.string()),
});

export const StoredSiteSpecSchema = z.object({
	siteId: z.number().int(),
	name: z.string(),
	shortName: z.string(),
	description: z.string(),
	settlement: StoredSettlementSpecSchema,
	npcs: z.array(StoredNpcSpecSchema),
	hooks: z.array(z.string()),
});

export const ScenarioArtifactSchema = z.object({
	artifactVersion: z.literal(ARTIFACT_VERSION),
	id: z
		.string()
		.min(1)
		.max(64)
		// The id is a filename stem and a value written into saves, so it must not be
		// able to walk out of the scenarios directory.
		.regex(/^[a-z0-9][a-z0-9-]*$/, "lower-case letters, digits and dashes only"),
	title: z.string().min(1).max(80),
	blurb: z.string().max(400),
	brief: ScenarioBriefSchema,
	seed: z.number().int(),
	spawn: z.object({ x: z.number().int(), y: z.number().int() }),
	bounds: WorldBoundsSchema,
	lore: StoredWorldLoreSchema,
	regions: z.record(z.string(), StoredRegionSpecSchema),
	sites: z.record(z.string(), StoredSiteSpecSchema),
	authoredWith: z.object({
		models: z.record(z.string(), z.string()),
		calls: z.number().int().min(0),
		at: z.string(),
	}),
});
