import { z } from "zod";
import { ActionSchema } from "../ai/dialogue/schema.js";
import { PLACEMENTS, STRUCTURE_KINDS } from "../ai/director/schemas.js";
import { PackOverrideSchema } from "../core/content/schema.js";
import { ConditionSchema, RequiresSchema } from "../core/rules/condition-schema.js";
import { MAX_SIGN_ARMS } from "../core/rules/signage.js";
import { WorldRecipeSchema } from "../core/world/recipe-schema.js";
import { ARTIFACT_VERSION } from "./artifact.js";

/**
 * What a scenario file on disk is allowed to contain.
 *
 * These validate the *persisted* shapes, which are not the same as the director's
 * response schemas: a `SiteSpec` carries its own `siteId` and a nested
 * `SettlementSpec`, whereas the model is asked for a flatter thing that the
 * director then assembles. Sharing the enums keeps the closed sets closed —
 * an artifact cannot smuggle in a structure kind the generator has no plan for,
 * however it was produced.
 *
 * An artifact is data from outside the program: it may have been hand-edited,
 * generated by an older build, or truncated by a full disk. It gets parsed, not
 * cast.
 */

const BoundaryStyleSchema = z.enum(["ocean", "cliffs", "mountains"]);

/**
 * A full screen of prose.
 *
 * Bounded generously but bounded: this is the one place in the game allowed to be
 * long, and the renderer elides what will not fit rather than growing the frame, so
 * a card nobody bounded would simply lose its ending.
 */
export const CardBodySchema = z.object({
	title: z.string().min(1).max(120),
	subtitle: z.string().max(160).optional(),
	sections: z
		.array(
			z.object({
				heading: z.string().min(1).max(40),
				body: z.string().min(1).max(900),
			}),
		)
		.min(1)
		.max(4),
});

/** A lock on a door, or on a gate. The same shape serves both. */
export const LockSchema = z.object({
	opensWhen: ConditionSchema,
	lockedText: z.string().min(1).max(200),
});

export const WorldBoundsSchema = z.object({
	minX: z.number().int(),
	minY: z.number().int(),
	maxX: z.number().int(),
	maxY: z.number().int(),
	style: BoundaryStyleSchema,
	thickness: z.number().int().min(1).max(64),
});

export const ScenarioBriefSchema = z.object({
	title: z.string().optional(),
	premise: z.string().optional(),
	setting: z.string().optional(),
	storyline: z.string().optional(),
	tone: z.string().optional(),
	protagonist: z.string().optional(),
	avoid: z.string().optional(),
	duration: z.enum(["tiny", "short", "medium", "long"]).optional(),
});

export const StoredWorldLoreSchema = z.object({
	title: z.string(),
	premise: z.string(),
	era: z.string(),
	tone: z.string(),
	factions: z.array(z.string()),
	deities: z.array(z.string()),
});

export const StoredRegionSpecSchema = z.object({
	id: z.string(),
	name: z.string(),
	blurb: z.string(),
	tone: z.string(),
	culture: z.string(),
	factionName: z.string().optional(),
	lore: z.array(z.string()),
	ambient: z.array(z.string()),
});

const StoredStructureSchema = z.object({
	kind: z.enum(STRUCTURE_KINDS),
	size: z.enum(["small", "medium", "large"]),
	importance: z.number().int().min(1).max(5),
	name: z.string().optional(),
	signText: z.string().optional(),
	/** What has to be true to get inside. Absent means the door simply opens. */
	lock: LockSchema.optional(),
	/** A handle, so a relation or a story beat can name this building. */
	id: z.string().optional(),
	/** Whether the settlement must contain this rather than substituting filler. */
	required: z.boolean().optional(),
});

export const StoredSettlementSpecSchema = z
	.object({
		name: z.string(),
		walled: z.boolean(),
		structures: z.array(StoredStructureSchema),
	})
	.superRefine((spec, ctx) => {
		// A duplicate explicit id is not a stylistic slip: `settlement.ts` keys both its
		// plot request and its spec lookup by this string, and a repeat lets one plot's
		// assignment silently answer to the *other* entry's spec — a required building can
		// vanish into filler with nothing downstream reporting it wrong. Only entries that
		// *have* an id are compared; an absent id gets its own collision-proof handle at
		// generation time and is none of this check's business.
		const seen = new Set<string>();
		spec.structures.forEach((structure, index) => {
			if (structure.id === undefined) return;
			if (seen.has(structure.id)) {
				ctx.addIssue({
					code: "custom",
					message: `duplicate structure id "${structure.id}"`,
					path: ["structures", index, "id"],
				});
				return;
			}
			seen.add(structure.id);
		});
	});

export const StoredNpcSpecSchema = z.object({
	slot: z.number().int().min(0),
	name: z.string(),
	role: z.string(),
	glyph: z.string().regex(/^[A-Za-z]$/),
	appearance: z.string(),
	persona: z.string(),
	disposition: z.number().int().min(-100).max(100),
	placement: z.enum(PLACEMENTS),
	structureName: z.string().optional(),
	knows: z.array(z.string()),
	/** Whether a model may improvise for them. Never for anybody the arc hangs on. */
	live: z.boolean().optional(),
	/** Speak with somebody else's written words, by their npcId. */
	treeAlias: z.string().min(1).max(64).optional(),
	/** What has to be true for this person to be in the world at all. */
	requires: ConditionSchema.optional(),
	/** Keep them at their own anchor at every hour, rather than on a schedule. */
	stays: z.boolean().optional(),
	/** Stand inside `structureName` rather than outdoors. */
	indoors: z.boolean().optional(),
});

export const StoredSiteSpecSchema = z.object({
	siteId: z.number().int(),
	name: z.string(),
	shortName: z.string(),
	description: z.string(),
	settlement: StoredSettlementSpecSchema,
	npcs: z.array(StoredNpcSpecSchema),
	hooks: z.array(z.string()),
});

const ObjectiveSchema = z.object({
	kind: z.enum(["reach", "talk", "have", "flag", "quest"]),
	target: z.string().min(1),
	quantity: z.number().int().min(1).optional(),
	done: z.boolean(),
});

export const BarrierSchema = z.object({
	id: z.string().min(1).max(64),
	/**
	 * Where the gate stands: every tile of it, or the name of one the generator makes.
	 *
	 * A list, because a road is rarely one tile wide. Or `{ siteId, at: "gate" }`, which
	 * is the better spelling wherever it applies: a castle's gatehouse is the only choke
	 * point the generator *guarantees*, and copying its three coordinates into a file by
	 * hand leaves nothing keeping the two in step — move the castle and the gate is left
	 * standing in a field, blocking nothing, with no complaint from anywhere.
	 */
	tiles: z.union([
		z
			.array(z.object({ x: z.number().int(), y: z.number().int() }))
			.min(1)
			.max(16),
		z.object({ siteId: z.number().int(), at: z.literal("gate") }).strict(),
	]),
	opensWhen: ConditionSchema,
	lockedText: z.string().min(1).max(200),
	opensText: z.string().min(1).max(200).optional(),
});

/**
 * The effects a scenario file is allowed to ask for.
 *
 * A deliberate subset of `DomainEffect`, not all of it. The ones left out are the
 * engine's own bookkeeping — `MeetNpc`, `RecordTurn`, `SetNpcNode`, `FoldNpcMemory`,
 * `EndDialogue` — which describe what the dialogue layer has just done rather than
 * something an author would ever want to cause. Letting a file write those would let it
 * fabricate a relationship the player never had, or close a conversation nobody opened.
 *
 * A closed union rather than the flat nullable shape `ActionSchema` uses, because that
 * shape exists to work around structured-output support for unions in model providers,
 * and a file on disk has no such constraint. An author gets to write the effect it
 * actually is.
 */
export const AuthoredEffectSchema = z.discriminatedUnion("t", [
	z.object({
		t: z.literal("SetFlag"),
		key: z.string().min(1).max(120),
		value: z.union([z.string().max(120), z.number(), z.boolean()]),
	}),
	z.object({
		t: z.literal("GrantItem"),
		name: z.string().min(1).max(60),
		description: z.string().min(1).max(200),
		quantity: z.number().int().min(1).max(99),
	}),
	z.object({
		t: z.literal("TakeItem"),
		name: z.string().min(1).max(60),
		quantity: z.number().int().min(1).max(99),
	}),
	z.object({ t: z.literal("AdjustGold"), amount: z.number().int().min(-9999).max(9999) }),
	z.object({
		t: z.literal("CreateQuest"),
		id: z.string().min(1).max(64),
		name: z.string().min(1).max(80),
		description: z.string().max(400),
		objectives: z.array(ObjectiveSchema).max(6),
		siteId: z.number().int().optional(),
		parentId: z.string().min(1).max(64).optional(),
	}),
	z.object({
		t: z.literal("AdvanceQuest"),
		id: z.string().min(1).max(64),
		note: z.string().min(1).max(240),
	}),
	z.object({ t: z.literal("CompleteQuest"), id: z.string().min(1).max(64) }),
	z.object({ t: z.literal("AbandonQuest"), id: z.string().min(1).max(64) }),
	z.object({
		t: z.literal("ShowCard"),
		card: CardBodySchema.extend({ id: z.string().min(1).max(64) }),
	}),
	z.object({
		t: z.literal("RecordJournal"),
		entry: z.object({
			kind: z.enum(["lore", "place", "rumor", "event"]),
			text: z.string().min(1).max(400),
			source: z.string().min(1).max(64).optional(),
		}),
	}),
	z.object({
		t: z.literal("AdjustReputation"),
		faction: z.string().min(1).max(60),
		delta: z.number().int().min(-100).max(100),
	}),
	z.object({
		t: z.literal("AdjustDisposition"),
		npcId: z.string().min(1).max(64),
		delta: z.number().int().min(-100).max(100),
	}),
	z.object({ t: z.literal("Heal"), amount: z.number().int().min(1).max(999) }),
	z.object({ t: z.literal("Damage"), amount: z.number().int().min(1).max(999) }),
	z.object({ t: z.literal("Teleport"), x: z.number().int(), y: z.number().int() }),
	z.object({ t: z.literal("OpenBarrier"), id: z.string().min(1).max(64) }),
	z.object({ t: z.literal("PlayScene"), id: z.string().min(1).max(64) }),
]);

export const TriggerSchema = z.object({
	id: z.string().min(1).max(64),
	when: ConditionSchema,
	once: z.boolean().optional(),
	effects: z.array(AuthoredEffectSchema).min(1).max(8),
});

const PlacementSiteSchema = z.union([
	z.object({ kind: z.literal("world"), x: z.number().int(), y: z.number().int() }),
	z.object({
		kind: z.literal("interior"),
		interiorId: z.number().int(),
		x: z.number().int().min(0),
		y: z.number().int().min(0),
		/** Which storey. Absent is the ground floor. */
		level: z.number().int().min(0).max(8).optional(),
	}),
	z.object({
		kind: z.literal("site"),
		siteId: z.number().int(),
		/** A building's proper name, or failing that its kind. */
		structure: z.string().min(1).max(60).optional(),
		anchor: z.enum(PLACEMENTS).optional(),
		/** Which storey of it. Absent is the ground floor. */
		level: z.number().int().min(0).max(8).optional(),
	}),
]);

export const PlacementSchema = z.object({
	id: z.string().min(1).max(64),
	at: PlacementSiteSchema,
	item: z.object({
		name: z.string().min(1).max(60),
		description: z.string().min(1).max(200),
		quantity: z.number().int().min(1).max(99).optional(),
	}),
	requires: ConditionSchema.optional(),
	showDecor: z.boolean().optional(),
	emptyText: z.string().min(1).max(200).optional(),
});

/**
 * A board on a post, as an author writes it.
 *
 * A tile and a list of site ids, and deliberately nothing else. There is no field here
 * for a direction or a distance because both are computed from where the sites really
 * are — see `core/rules/signage.ts` — so the one thing a signpost must never do, which is
 * point the wrong way, is not expressible.
 */
export const SignSchema = z.object({
	id: z.string().min(1).max(64),
	x: z.number().int(),
	y: z.number().int(),
	arms: z
		.array(
			z.object({
				siteId: z.number().int(),
				label: z.string().min(1).max(60).optional(),
			}),
		)
		.min(1)
		.max(MAX_SIGN_ARMS),
	note: z.string().min(1).max(120).optional(),
});

/**
 * The clock, as an author writes it.
 *
 * Every field optional, because the world that says anything at all here is the
 * unusual one and it usually says one thing: `{ "enabled": false }`.
 */
export const TimeOptionsSchema = z.object({
	enabled: z.boolean().optional(),
	startHour: z.number().int().min(0).max(23).optional(),
	ticksPerHour: z.number().int().min(1).max(600).optional(),
	lighting: z.boolean().optional(),
	schedules: z.boolean().optional(),
	weather: z.boolean().optional(),
});

export const ScenarioBeatSchema = z.object({
	id: z.string().min(1).max(64),
	order: z.number().int().min(0),
	siteId: z.number().int(),
	npcSlot: z.number().int().min(0),
	requires: RequiresSchema,
	setsFlag: z.string().min(1),
	/** Opens on its own once this is true, rather than on a conversation. */
	opensOn: ConditionSchema.optional(),
	/** A fork this beat is one arm of. Siblings are barred once one is taken. */
	branch: z.string().min(1).max(64).optional(),
	/** A side errand: shown, but not counted toward the story being told. */
	optional: z.boolean().optional(),
	quest: z
		.object({
			id: z.string().min(1).max(64),
			name: z.string().min(1),
			description: z.string(),
			objectives: z.array(ObjectiveSchema),
			parentId: z.string().min(1).max(64).optional(),
		})
		.optional(),
	journal: z.string().optional(),
	card: CardBodySchema.optional(),
	/** What else the beat does to the world as it opens. */
	effects: z.array(AuthoredEffectSchema).max(8).optional(),
});

export const ScenarioArcSchema = z.object({
	title: z.string().min(1).max(120),
	premise: z.string().max(600),
	beats: z.array(ScenarioBeatSchema),
	ending: CardBodySchema.optional(),
	/**
	 * Outcomes to choose between, first match in author order.
	 *
	 * An entry with no `when` always matches, which is how the last one becomes the
	 * catch-all — and why the list is ordered rather than scored.
	 */
	endings: z
		.array(
			CardBodySchema.extend({ id: z.string().min(1).max(64), when: ConditionSchema.optional() }),
		)
		.max(8)
		.optional(),
});

const DialogueChoiceSchema = z.object({
	text: z.string().min(1).max(120),
	goto: z.string().max(64).nullable(),
	requires: RequiresSchema.optional(),
});

export const DialogueNodeSchema = z.object({
	id: z.string().min(1).max(64),
	speech: z.string().max(600),
	requires: RequiresSchema.optional(),
	choices: z.array(DialogueChoiceSchema).max(6),
	// Four. A hand-over is take, give, warm, and record — and the record is the one
	// that stops the next hello asking for the thing again, so it must fit.
	actions: z.array(ActionSchema).max(4).optional(),
});

export const DialogueTreeSchema = z.object({
	npcId: z.string().min(1),
	entry: z.array(z.string().min(1)).min(1),
	revisit: z.array(z.string().min(1)).optional(),
	nodes: z.record(z.string(), DialogueNodeSchema),
});

/**
 * Where a scene puts something.
 *
 * Not `PlacementSiteSchema`, although they look alike: a placement's site spelling resolves
 * *inside* a building, and a cutscene happens outdoors. See `ScenePoint`.
 */
const ScenePointSchema = z.discriminatedUnion("kind", [
	z.object({ kind: z.literal("world"), x: z.number().int(), y: z.number().int() }),
	z.object({
		kind: z.literal("anchor"),
		siteId: z.number().int(),
		anchor: z.enum(PLACEMENTS),
	}),
	z.object({
		kind: z.literal("door"),
		siteId: z.number().int(),
		structure: z.string().min(1).max(60),
	}),
]);

/**
 * One thing a scene does.
 *
 * `Effects` reuses `AuthoredEffectSchema`, so a scene can cause exactly what a trigger can
 * and nothing more — including, in principle, another `PlayScene`. That is refused by
 * `sceneEffectProblems`' sibling check rather than by the schema, because the message a
 * scene starting a scene deserves is a sentence, not a parse error.
 */
const SceneActionSchema = z.discriminatedUnion("t", [
	z.object({
		t: z.literal("Camera"),
		to: ScenePointSchema,
		pan: z.enum(["cut", "slow", "fast"]).optional(),
	}),
	z.object({ t: z.literal("Spawn"), actor: z.string().min(1).max(40), at: ScenePointSchema }),
	z.object({ t: z.literal("Despawn"), actor: z.string().min(1).max(40) }),
	z.object({
		t: z.literal("WalkTo"),
		actor: z.string().min(1).max(40),
		to: ScenePointSchema,
		speed: z.enum(["slow", "normal", "fast"]).optional(),
	}),
	z.object({
		t: z.literal("Face"),
		actor: z.string().min(1).max(40),
		at: z.union([ScenePointSchema, z.enum(["up", "down", "left", "right"])]),
	}),
	// Shorter than a card and longer than a status line: a caption is one thing somebody
	// says while the world holds still, and a paragraph in that position cannot be read.
	z.object({
		t: z.literal("Say"),
		actor: z.string().min(1).max(40),
		text: z.string().min(1).max(240),
	}),
	z.object({
		t: z.literal("Card"),
		card: CardBodySchema.extend({ id: z.string().min(1).max(64) }),
	}),
	z.object({ t: z.literal("Wait"), ticks: z.number().int().min(1).max(120) }),
	z.object({ t: z.literal("Effects"), effects: z.array(AuthoredEffectSchema).min(1).max(8) }),
]);

export const SceneSchema = z.object({
	id: z.string().min(1).max(64),
	cast: z.record(z.string().min(1).max(40), z.string().min(1).max(64)).optional(),
	// Twenty-four steps is a long cutscene — a minute of watching — and past that a scene is
	// really a chapter and wants to be two, with the player given the world back in between.
	steps: z
		.array(
			z.object({
				do: z.array(SceneActionSchema).min(1).max(8),
				hold: z.number().int().min(1).max(120).optional(),
			}),
		)
		.min(1)
		.max(24),
	skippable: z.boolean().optional(),
});

const PointSchema = z.object({ x: z.number().int(), y: z.number().int() });

export const TerraformEditSchema = z.discriminatedUnion("t", [
	z.object({
		t: z.literal("Path"),
		id: z.string().min(1).max(64),
		from: PointSchema,
		to: PointSchema,
		width: z.number().int().min(1).max(9).optional(),
		surface: z.enum(["path", "dirt", "cobble"]),
	}),
	z.object({
		t: z.literal("Bridge"),
		id: z.string().min(1).max(64),
		from: PointSchema,
		to: PointSchema,
	}),
	z.object({
		t: z.literal("Clearing"),
		id: z.string().min(1).max(64),
		at: PointSchema,
		radius: z.number().int().min(1).max(24),
	}),
]);

/**
 * A diff over a list of things with ids.
 *
 * Generic so the six lists a phase can change share one shape, and so that a phase file
 * reads the same whichever of them it is touching.
 */
const diffOf = <T extends z.ZodTypeAny>(item: T) =>
	z.object({
		add: z.array(item).max(64).optional(),
		remove: z.array(z.string().min(1).max(64)).max(64).optional(),
		replace: z.array(item).max(64).optional(),
	});

export const PhaseSchema = z.object({
	id: z.string().min(1).max(64),
	name: z.string().min(1).max(80),
	// Optional in the type because the base content shares it, but every phase *file* has one:
	// a later chapter with no condition would be in force from the first frame. `readScenarioDir`
	// refuses one without it.
	when: ConditionSchema.optional(),
	sites: diffOf(StoredSiteSpecSchema).optional(),
	placements: diffOf(PlacementSchema).optional(),
	signs: diffOf(SignSchema).optional(),
	barriers: diffOf(BarrierSchema).optional(),
	triggers: diffOf(TriggerSchema).optional(),
	terraform: diffOf(TerraformEditSchema).optional(),
	trees: z.record(z.string(), DialogueTreeSchema.nullable()).optional(),
	scenes: z.record(z.string(), SceneSchema.nullable()).optional(),
	beats: z.array(ScenarioBeatSchema).max(12).optional(),
});

export const ScenarioArtifactSchema = z.object({
	artifactVersion: z.literal(ARTIFACT_VERSION),
	id: z
		.string()
		.min(1)
		.max(64)
		// The id is a filename stem and a value written into saves, so it must not be
		// able to walk out of the scenarios directory.
		.regex(/^[a-z0-9][a-z0-9-]*$/, "lower-case letters, digits and dashes only"),
	title: z.string().min(1).max(80),
	blurb: z.string().max(400),
	brief: ScenarioBriefSchema,
	// A pack name, resolved against `.packs/`. Constrained like the scenario id
	// because it becomes a filename, and a name that can walk up out of the packs
	// directory would let a scenario file choose what gets read.
	pack: z
		.string()
		.min(1)
		.max(64)
		.regex(/^[a-z0-9][a-z0-9-]*$/, "lower-case letters, digits and dashes only")
		.optional(),
	content: PackOverrideSchema.optional(),
	// A tile pack directory under `.packs/tiles/`, constrained like the other names
	// because it becomes a path.
	tiles: z
		.string()
		.min(1)
		.max(64)
		.regex(/^[a-z0-9][a-z0-9-]*$/, "lower-case letters, digits and dashes only")
		.optional(),
	seed: z.number().int(),
	recipe: WorldRecipeSchema.optional(),
	spawn: z.object({ x: z.number().int(), y: z.number().int() }),
	bounds: WorldBoundsSchema,
	lore: StoredWorldLoreSchema,
	regions: z.record(z.string(), StoredRegionSpecSchema),
	sites: z.record(z.string(), StoredSiteSpecSchema),
	arc: ScenarioArcSchema.optional(),
	triggers: z.array(TriggerSchema).max(64).optional(),
	barriers: z.array(BarrierSchema).max(32).optional(),
	placements: z.array(PlacementSchema).max(64).optional(),
	signs: z.array(SignSchema).max(32).optional(),
	terraform: z.array(TerraformEditSchema).max(64).optional(),
	scenes: z.record(z.string(), SceneSchema).optional(),
	phases: z.array(PhaseSchema).max(8).optional(),
	/** Whether this world has a clock. Absent means the ordinary day/night cycle. */
	time: TimeOptionsSchema.optional(),
	/** Whether a model may improvise for anyone with no written tree. Absent means no. */
	liveInGame: z.boolean().optional(),
	/**
	 * What the player is carrying when the world opens. Absent means a handful of coins.
	 *
	 * Capped at eight, because a starting pack is a premise rather than a warehouse: the
	 * player has to be able to read the whole of it on the first screen they open.
	 */
	startsWith: z
		.array(
			z
				.object({
					name: z.string().min(1).max(48),
					description: z.string().min(1).max(240),
					quantity: z.number().int().min(1).max(999),
				})
				.strict(),
		)
		.max(8)
		.optional(),
	trees: z.record(z.string(), DialogueTreeSchema).optional(),
	authoredWith: z.object({
		models: z.record(z.string(), z.string()),
		calls: z.number().int().min(0),
		at: z.string(),
	}),
});
